---
- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure curl is installed
  ansible.builtin.apt:
    name: curl
    state: present