name: Ansible CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Network
      run: docker network create ansible-network

    - name: Run target containers
      run: |
        docker run -d --name web01 --network ansible-network debian:bullseye-slim sleep 3600
        docker run -d --name web02 --network ansible-network debian:bullseye-slim sleep 3600
        docker run -d --name lb01 --network ansible-network -p 8080:80 debian:bullseye-slim sleep 3600

    - name: Install collection and Run Ansible Playbook
      run: |
        docker run --rm --network ansible-network \
        -v ${{ github.workspace }}:/ansible \
        -w /ansible \
        quay.io/ansible/ansible-runner \
        sh -c "ansible-galaxy collection install community.docker && ansible-playbook -i inventory.ini site.yml"

    - name: Verify Deployment from within the Runner
      run: |
        echo "The application is running inside the GitHub Actions runner."
        echo "The following 'curl' commands test the load balancer from within that environment."
        echo "This URL is NOT accessible from your local browser."
        echo "-----------------------------------------------------"
        sleep 10
        echo "Running verification test 1..."
        curl --fail http://localhost:8080
        echo
        echo "Running verification test 2..."
        curl --fail http://localhost:8080
        echo
        echo "-----------------------------------------------------"
        echo "Verification successful!"