name: Self-Hosted Ansible CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # This is the key change: it tells GitHub to send this job to a runner
    # that has BOTH the "self-hosted" and "hostalien" labels.
    runs-on: [self-hosted, hostalien]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean up old resources and Set up Network
      run: |
        docker stop web01 web02 lb01 || true
        docker rm web01 web02 lb01 || true
        docker network rm ansible-network || true
        docker network create ansible-network

    - name: Run target containers
      run: |
        docker run -d --name web01 --network ansible-network debian:bullseye-slim sleep 3600
        docker run -d --name web02 --network ansible-network debian:bullseye-slim sleep 3600
        docker run -d --name lb01 --network ansible-network -p 8080:80 debian:bullseye-slim sleep 3600

    - name: Run Ansible Playbook Directly on Runner
      run: |
        # We can run ansible-playbook directly because it's installed on the runner (your WSL system).
        # We don't need to use a separate ansible-runner container.
        ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i inventory.ini site.yml

    - name: Verify Deployment
      run: |
        echo "Waiting for services to be available..."
        sleep 10
        echo "Running verification tests..."
        curl --fail http://localhost:8080
        curl --fail http://localhost:8080
        echo
        echo "Verification successful!"
